#!/usr/bin/env bash
set -euo pipefail
cd kernel_workspace/kernel_platform

export PATH="/usr/lib/ccache:$PATH"
export ARCH=arm64
export LLVM=1
export LLVM_IAS=1

if [[ "$CCACHE_MODE" == "Use CCache" ]]; then
  export CCACHE_DIR="$HOME/.cache/ccache"
  mkdir -p "$CCACHE_DIR"
fi


# Kleaf's --defconfig_fragment consumes a Bazel label. Ensure the generated
# fragment is exported by the //common package even if another step recreated
# BUILD.bazel after features.sh ran.
COMMON_BUILD="$PWD/common/BUILD.bazel"
FRAGMENT_REL="arch/arm64/configs/oneplus_features_defconfig"
if [[ -n "${FEATURE_FRAGMENT_LABEL:-}" && -f "$COMMON_BUILD" && -f "common/$FRAGMENT_REL" ]]; then
  if ! grep -qE 'name[[:space:]]*=[[:space:]]*"oneplus_features_defconfig"' "$COMMON_BUILD"; then
    cat >> "$COMMON_BUILD" <<'EOF'

# Generated by the OnePlus Universal Kernel workflow.
exports_files([
    "arch/arm64/configs/oneplus_features_defconfig",
])
EOF
  fi
fi

if [[ "$BUILD_SYSTEM" == bazel ]]; then
  mkdir -p "$PWD/out/dist"
  if [[ "$KERNEL_VERSION" == 6.12* ]]; then
    tools/bazel run --config=fast --config=stamp \
      --defconfig_fragment="$FEATURE_FRAGMENT_LABEL" \
      --verbose_failures \
      //common:kernel_aarch64_dist -- --destdir="$PWD/out/dist"
  else
    tools/bazel run --config=fast --config=stamp \
      --defconfig_fragment="$FEATURE_FRAGMENT_LABEL" \
      --verbose_failures \
      //common:kernel_aarch64_dist -- --destdir="$PWD/out/dist"
  fi
elif [[ "$BUILD_SYSTEM" == buildsh ]]; then
  if [[ -f build/build.sh ]]; then
    BUILD_CONFIG="${BUILD_CONFIG:-common/build.config.gki.aarch64}" \
      LTO=thin \
      OUT_DIR="$PWD/out" \
      build/build.sh -j"$(nproc)"
  else
    echo "build.sh is unavailable." >&2
    exit 1
  fi
fi
